// File generated from our OpenAPI spec by Stainless.

package dm.sent.models.templates

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import dm.sent.core.jsonMapper
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class SentDmServicesCommonContractsPocOsTemplateBodyTest {

    @Test
    fun create() {
        val sentDmServicesCommonContractsPocOsTemplateBody =
            SentDmServicesCommonContractsPocOsTemplateBody.builder()
                .multiChannel(
                    TemplateBodyContent.builder()
                        .template("template")
                        .type("type")
                        .addVariable(
                            TemplateVariable.builder()
                                .name("x")
                                .props(
                                    TemplateVariable.Props.builder()
                                        .mediaType("x")
                                        .sample("x")
                                        .url("x")
                                        .variableType("x")
                                        .alt("alt")
                                        .regex("regex")
                                        .shortUrl("shortUrl")
                                        .build()
                                )
                                .type("x")
                                .id(0)
                                .build()
                        )
                        .build()
                )
                .sms(
                    TemplateBodyContent.builder()
                        .template("template")
                        .type("type")
                        .addVariable(
                            TemplateVariable.builder()
                                .name("x")
                                .props(
                                    TemplateVariable.Props.builder()
                                        .mediaType("x")
                                        .sample("x")
                                        .url("x")
                                        .variableType("x")
                                        .alt("alt")
                                        .regex("regex")
                                        .shortUrl("shortUrl")
                                        .build()
                                )
                                .type("x")
                                .id(0)
                                .build()
                        )
                        .build()
                )
                .whatsapp(
                    TemplateBodyContent.builder()
                        .template("template")
                        .type("type")
                        .addVariable(
                            TemplateVariable.builder()
                                .name("x")
                                .props(
                                    TemplateVariable.Props.builder()
                                        .mediaType("x")
                                        .sample("x")
                                        .url("x")
                                        .variableType("x")
                                        .alt("alt")
                                        .regex("regex")
                                        .shortUrl("shortUrl")
                                        .build()
                                )
                                .type("x")
                                .id(0)
                                .build()
                        )
                        .build()
                )
                .build()

        assertThat(sentDmServicesCommonContractsPocOsTemplateBody.multiChannel())
            .contains(
                TemplateBodyContent.builder()
                    .template("template")
                    .type("type")
                    .addVariable(
                        TemplateVariable.builder()
                            .name("x")
                            .props(
                                TemplateVariable.Props.builder()
                                    .mediaType("x")
                                    .sample("x")
                                    .url("x")
                                    .variableType("x")
                                    .alt("alt")
                                    .regex("regex")
                                    .shortUrl("shortUrl")
                                    .build()
                            )
                            .type("x")
                            .id(0)
                            .build()
                    )
                    .build()
            )
        assertThat(sentDmServicesCommonContractsPocOsTemplateBody.sms())
            .contains(
                TemplateBodyContent.builder()
                    .template("template")
                    .type("type")
                    .addVariable(
                        TemplateVariable.builder()
                            .name("x")
                            .props(
                                TemplateVariable.Props.builder()
                                    .mediaType("x")
                                    .sample("x")
                                    .url("x")
                                    .variableType("x")
                                    .alt("alt")
                                    .regex("regex")
                                    .shortUrl("shortUrl")
                                    .build()
                            )
                            .type("x")
                            .id(0)
                            .build()
                    )
                    .build()
            )
        assertThat(sentDmServicesCommonContractsPocOsTemplateBody.whatsapp())
            .contains(
                TemplateBodyContent.builder()
                    .template("template")
                    .type("type")
                    .addVariable(
                        TemplateVariable.builder()
                            .name("x")
                            .props(
                                TemplateVariable.Props.builder()
                                    .mediaType("x")
                                    .sample("x")
                                    .url("x")
                                    .variableType("x")
                                    .alt("alt")
                                    .regex("regex")
                                    .shortUrl("shortUrl")
                                    .build()
                            )
                            .type("x")
                            .id(0)
                            .build()
                    )
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val sentDmServicesCommonContractsPocOsTemplateBody =
            SentDmServicesCommonContractsPocOsTemplateBody.builder()
                .multiChannel(
                    TemplateBodyContent.builder()
                        .template("template")
                        .type("type")
                        .addVariable(
                            TemplateVariable.builder()
                                .name("x")
                                .props(
                                    TemplateVariable.Props.builder()
                                        .mediaType("x")
                                        .sample("x")
                                        .url("x")
                                        .variableType("x")
                                        .alt("alt")
                                        .regex("regex")
                                        .shortUrl("shortUrl")
                                        .build()
                                )
                                .type("x")
                                .id(0)
                                .build()
                        )
                        .build()
                )
                .sms(
                    TemplateBodyContent.builder()
                        .template("template")
                        .type("type")
                        .addVariable(
                            TemplateVariable.builder()
                                .name("x")
                                .props(
                                    TemplateVariable.Props.builder()
                                        .mediaType("x")
                                        .sample("x")
                                        .url("x")
                                        .variableType("x")
                                        .alt("alt")
                                        .regex("regex")
                                        .shortUrl("shortUrl")
                                        .build()
                                )
                                .type("x")
                                .id(0)
                                .build()
                        )
                        .build()
                )
                .whatsapp(
                    TemplateBodyContent.builder()
                        .template("template")
                        .type("type")
                        .addVariable(
                            TemplateVariable.builder()
                                .name("x")
                                .props(
                                    TemplateVariable.Props.builder()
                                        .mediaType("x")
                                        .sample("x")
                                        .url("x")
                                        .variableType("x")
                                        .alt("alt")
                                        .regex("regex")
                                        .shortUrl("shortUrl")
                                        .build()
                                )
                                .type("x")
                                .id(0)
                                .build()
                        )
                        .build()
                )
                .build()

        val roundtrippedSentDmServicesCommonContractsPocOsTemplateBody =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(sentDmServicesCommonContractsPocOsTemplateBody),
                jacksonTypeRef<SentDmServicesCommonContractsPocOsTemplateBody>(),
            )

        assertThat(roundtrippedSentDmServicesCommonContractsPocOsTemplateBody)
            .isEqualTo(sentDmServicesCommonContractsPocOsTemplateBody)
    }
}
