// File generated from our OpenAPI spec by Stainless.

package dm.sent.models.templates

import dm.sent.core.http.Headers
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class TemplateCreateParamsTest {

    @Test
    fun create() {
        TemplateCreateParams.builder()
            .idempotencyKey("req_abc123_retry1")
            .xProfileId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
            .category("MARKETING")
            .creationSource(null)
            .definition(
                TemplateCreateParams.Definition.builder()
                    .body(
                        TemplateCreateParams.Definition.Body.builder()
                            .multiChannel(
                                TemplateCreateParams.Definition.Body.MultiChannel.builder()
                                    .template("Hello {{0:variable}}! Welcome to {{1:variable}}.")
                                    .type(null)
                                    .addVariable(
                                        TemplateCreateParams.Definition.Body.MultiChannel.Variable
                                            .builder()
                                            .name("name")
                                            .props(
                                                TemplateCreateParams.Definition.Body.MultiChannel
                                                    .Variable
                                                    .Props
                                                    .builder()
                                                    .mediaType("x")
                                                    .sample("John")
                                                    .url("x")
                                                    .variableType("text")
                                                    .alt(null)
                                                    .regex(null)
                                                    .shortUrl(null)
                                                    .build()
                                            )
                                            .type("variable")
                                            .id(0)
                                            .build()
                                    )
                                    .addVariable(
                                        TemplateCreateParams.Definition.Body.MultiChannel.Variable
                                            .builder()
                                            .name("company")
                                            .props(
                                                TemplateCreateParams.Definition.Body.MultiChannel
                                                    .Variable
                                                    .Props
                                                    .builder()
                                                    .mediaType("x")
                                                    .sample("SentDM")
                                                    .url("x")
                                                    .variableType("text")
                                                    .alt(null)
                                                    .regex(null)
                                                    .shortUrl(null)
                                                    .build()
                                            )
                                            .type("variable")
                                            .id(1)
                                            .build()
                                    )
                                    .build()
                            )
                            .rcs(
                                TemplateCreateParams.Definition.Body.Rcs.builder()
                                    .template("template")
                                    .type("type")
                                    .addVariable(
                                        TemplateCreateParams.Definition.Body.Rcs.Variable.builder()
                                            .name("x")
                                            .props(
                                                TemplateCreateParams.Definition.Body.Rcs.Variable
                                                    .Props
                                                    .builder()
                                                    .mediaType("x")
                                                    .sample("x")
                                                    .url("x")
                                                    .variableType("x")
                                                    .alt("alt")
                                                    .regex("regex")
                                                    .shortUrl("shortUrl")
                                                    .build()
                                            )
                                            .type("x")
                                            .id(0)
                                            .build()
                                    )
                                    .build()
                            )
                            .sms(
                                TemplateCreateParams.Definition.Body.Sms.builder()
                                    .template("template")
                                    .type("type")
                                    .addVariable(
                                        TemplateCreateParams.Definition.Body.Sms.Variable.builder()
                                            .name("x")
                                            .props(
                                                TemplateCreateParams.Definition.Body.Sms.Variable
                                                    .Props
                                                    .builder()
                                                    .mediaType("x")
                                                    .sample("x")
                                                    .url("x")
                                                    .variableType("x")
                                                    .alt("alt")
                                                    .regex("regex")
                                                    .shortUrl("shortUrl")
                                                    .build()
                                            )
                                            .type("x")
                                            .id(0)
                                            .build()
                                    )
                                    .build()
                            )
                            .whatsapp(
                                TemplateCreateParams.Definition.Body.Whatsapp.builder()
                                    .template("template")
                                    .type("type")
                                    .addVariable(
                                        TemplateCreateParams.Definition.Body.Whatsapp.Variable
                                            .builder()
                                            .name("x")
                                            .props(
                                                TemplateCreateParams.Definition.Body.Whatsapp
                                                    .Variable
                                                    .Props
                                                    .builder()
                                                    .mediaType("x")
                                                    .sample("x")
                                                    .url("x")
                                                    .variableType("x")
                                                    .alt("alt")
                                                    .regex("regex")
                                                    .shortUrl("shortUrl")
                                                    .build()
                                            )
                                            .type("x")
                                            .id(0)
                                            .build()
                                    )
                                    .build()
                            )
                            .build()
                    )
                    .authenticationConfig(
                        TemplateCreateParams.Definition.AuthenticationConfig.builder()
                            .addSecurityRecommendation(true)
                            .codeExpirationMinutes(0)
                            .build()
                    )
                    .addButton(
                        TemplateCreateParams.Definition.Button.builder()
                            .props(
                                TemplateCreateParams.Definition.Button.Props.builder()
                                    .activeFor(1)
                                    .countryCode("x")
                                    .offerCode("x")
                                    .phoneNumber("x")
                                    .quickReplyType("x")
                                    .text("text")
                                    .url("x")
                                    .urlType("x")
                                    .autofillText("autofillText")
                                    .otpType("otpType")
                                    .packageName("packageName")
                                    .signatureHash("signatureHash")
                                    .build()
                            )
                            .type("x")
                            .id(0)
                            .build()
                    )
                    .definitionVersion("1.0")
                    .footer(
                        TemplateCreateParams.Definition.Footer.builder()
                            .template("template")
                            .type("type")
                            .addVariable(
                                TemplateCreateParams.Definition.Footer.Variable.builder()
                                    .name("x")
                                    .props(
                                        TemplateCreateParams.Definition.Footer.Variable.Props
                                            .builder()
                                            .mediaType("x")
                                            .sample("x")
                                            .url("x")
                                            .variableType("x")
                                            .alt("alt")
                                            .regex("regex")
                                            .shortUrl("shortUrl")
                                            .build()
                                    )
                                    .type("x")
                                    .id(0)
                                    .build()
                            )
                            .build()
                    )
                    .header(
                        TemplateCreateParams.Definition.Header.builder()
                            .template("template")
                            .type("type")
                            .addVariable(
                                TemplateCreateParams.Definition.Header.Variable.builder()
                                    .name("x")
                                    .props(
                                        TemplateCreateParams.Definition.Header.Variable.Props
                                            .builder()
                                            .mediaType("x")
                                            .sample("x")
                                            .url("x")
                                            .variableType("x")
                                            .alt("alt")
                                            .regex("regex")
                                            .shortUrl("shortUrl")
                                            .build()
                                    )
                                    .type("x")
                                    .id(0)
                                    .build()
                            )
                            .build()
                    )
                    .build()
            )
            .language("en_US")
            .sandbox(false)
            .submitForReview(false)
            .build()
    }

    @Test
    fun headers() {
        val params =
            TemplateCreateParams.builder()
                .idempotencyKey("req_abc123_retry1")
                .xProfileId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .category("MARKETING")
                .creationSource(null)
                .definition(
                    TemplateCreateParams.Definition.builder()
                        .body(
                            TemplateCreateParams.Definition.Body.builder()
                                .multiChannel(
                                    TemplateCreateParams.Definition.Body.MultiChannel.builder()
                                        .template(
                                            "Hello {{0:variable}}! Welcome to {{1:variable}}."
                                        )
                                        .type(null)
                                        .addVariable(
                                            TemplateCreateParams.Definition.Body.MultiChannel
                                                .Variable
                                                .builder()
                                                .name("name")
                                                .props(
                                                    TemplateCreateParams.Definition.Body
                                                        .MultiChannel
                                                        .Variable
                                                        .Props
                                                        .builder()
                                                        .mediaType("x")
                                                        .sample("John")
                                                        .url("x")
                                                        .variableType("text")
                                                        .alt(null)
                                                        .regex(null)
                                                        .shortUrl(null)
                                                        .build()
                                                )
                                                .type("variable")
                                                .id(0)
                                                .build()
                                        )
                                        .addVariable(
                                            TemplateCreateParams.Definition.Body.MultiChannel
                                                .Variable
                                                .builder()
                                                .name("company")
                                                .props(
                                                    TemplateCreateParams.Definition.Body
                                                        .MultiChannel
                                                        .Variable
                                                        .Props
                                                        .builder()
                                                        .mediaType("x")
                                                        .sample("SentDM")
                                                        .url("x")
                                                        .variableType("text")
                                                        .alt(null)
                                                        .regex(null)
                                                        .shortUrl(null)
                                                        .build()
                                                )
                                                .type("variable")
                                                .id(1)
                                                .build()
                                        )
                                        .build()
                                )
                                .rcs(
                                    TemplateCreateParams.Definition.Body.Rcs.builder()
                                        .template("template")
                                        .type("type")
                                        .addVariable(
                                            TemplateCreateParams.Definition.Body.Rcs.Variable
                                                .builder()
                                                .name("x")
                                                .props(
                                                    TemplateCreateParams.Definition.Body.Rcs
                                                        .Variable
                                                        .Props
                                                        .builder()
                                                        .mediaType("x")
                                                        .sample("x")
                                                        .url("x")
                                                        .variableType("x")
                                                        .alt("alt")
                                                        .regex("regex")
                                                        .shortUrl("shortUrl")
                                                        .build()
                                                )
                                                .type("x")
                                                .id(0)
                                                .build()
                                        )
                                        .build()
                                )
                                .sms(
                                    TemplateCreateParams.Definition.Body.Sms.builder()
                                        .template("template")
                                        .type("type")
                                        .addVariable(
                                            TemplateCreateParams.Definition.Body.Sms.Variable
                                                .builder()
                                                .name("x")
                                                .props(
                                                    TemplateCreateParams.Definition.Body.Sms
                                                        .Variable
                                                        .Props
                                                        .builder()
                                                        .mediaType("x")
                                                        .sample("x")
                                                        .url("x")
                                                        .variableType("x")
                                                        .alt("alt")
                                                        .regex("regex")
                                                        .shortUrl("shortUrl")
                                                        .build()
                                                )
                                                .type("x")
                                                .id(0)
                                                .build()
                                        )
                                        .build()
                                )
                                .whatsapp(
                                    TemplateCreateParams.Definition.Body.Whatsapp.builder()
                                        .template("template")
                                        .type("type")
                                        .addVariable(
                                            TemplateCreateParams.Definition.Body.Whatsapp.Variable
                                                .builder()
                                                .name("x")
                                                .props(
                                                    TemplateCreateParams.Definition.Body.Whatsapp
                                                        .Variable
                                                        .Props
                                                        .builder()
                                                        .mediaType("x")
                                                        .sample("x")
                                                        .url("x")
                                                        .variableType("x")
                                                        .alt("alt")
                                                        .regex("regex")
                                                        .shortUrl("shortUrl")
                                                        .build()
                                                )
                                                .type("x")
                                                .id(0)
                                                .build()
                                        )
                                        .build()
                                )
                                .build()
                        )
                        .authenticationConfig(
                            TemplateCreateParams.Definition.AuthenticationConfig.builder()
                                .addSecurityRecommendation(true)
                                .codeExpirationMinutes(0)
                                .build()
                        )
                        .addButton(
                            TemplateCreateParams.Definition.Button.builder()
                                .props(
                                    TemplateCreateParams.Definition.Button.Props.builder()
                                        .activeFor(1)
                                        .countryCode("x")
                                        .offerCode("x")
                                        .phoneNumber("x")
                                        .quickReplyType("x")
                                        .text("text")
                                        .url("x")
                                        .urlType("x")
                                        .autofillText("autofillText")
                                        .otpType("otpType")
                                        .packageName("packageName")
                                        .signatureHash("signatureHash")
                                        .build()
                                )
                                .type("x")
                                .id(0)
                                .build()
                        )
                        .definitionVersion("1.0")
                        .footer(
                            TemplateCreateParams.Definition.Footer.builder()
                                .template("template")
                                .type("type")
                                .addVariable(
                                    TemplateCreateParams.Definition.Footer.Variable.builder()
                                        .name("x")
                                        .props(
                                            TemplateCreateParams.Definition.Footer.Variable.Props
                                                .builder()
                                                .mediaType("x")
                                                .sample("x")
                                                .url("x")
                                                .variableType("x")
                                                .alt("alt")
                                                .regex("regex")
                                                .shortUrl("shortUrl")
                                                .build()
                                        )
                                        .type("x")
                                        .id(0)
                                        .build()
                                )
                                .build()
                        )
                        .header(
                            TemplateCreateParams.Definition.Header.builder()
                                .template("template")
                                .type("type")
                                .addVariable(
                                    TemplateCreateParams.Definition.Header.Variable.builder()
                                        .name("x")
                                        .props(
                                            TemplateCreateParams.Definition.Header.Variable.Props
                                                .builder()
                                                .mediaType("x")
                                                .sample("x")
                                                .url("x")
                                                .variableType("x")
                                                .alt("alt")
                                                .regex("regex")
                                                .shortUrl("shortUrl")
                                                .build()
                                        )
                                        .type("x")
                                        .id(0)
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .language("en_US")
                .sandbox(false)
                .submitForReview(false)
                .build()

        val headers = params._headers()

        assertThat(headers)
            .isEqualTo(
                Headers.builder()
                    .put("Idempotency-Key", "req_abc123_retry1")
                    .put("x-profile-id", "182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .build()
            )
    }

    @Test
    fun headersWithoutOptionalFields() {
        val params = TemplateCreateParams.builder().build()

        val headers = params._headers()

        assertThat(headers).isEqualTo(Headers.builder().build())
    }

    @Test
    fun body() {
        val params =
            TemplateCreateParams.builder()
                .idempotencyKey("req_abc123_retry1")
                .xProfileId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .category("MARKETING")
                .creationSource(null)
                .definition(
                    TemplateCreateParams.Definition.builder()
                        .body(
                            TemplateCreateParams.Definition.Body.builder()
                                .multiChannel(
                                    TemplateCreateParams.Definition.Body.MultiChannel.builder()
                                        .template(
                                            "Hello {{0:variable}}! Welcome to {{1:variable}}."
                                        )
                                        .type(null)
                                        .addVariable(
                                            TemplateCreateParams.Definition.Body.MultiChannel
                                                .Variable
                                                .builder()
                                                .name("name")
                                                .props(
                                                    TemplateCreateParams.Definition.Body
                                                        .MultiChannel
                                                        .Variable
                                                        .Props
                                                        .builder()
                                                        .mediaType("x")
                                                        .sample("John")
                                                        .url("x")
                                                        .variableType("text")
                                                        .alt(null)
                                                        .regex(null)
                                                        .shortUrl(null)
                                                        .build()
                                                )
                                                .type("variable")
                                                .id(0)
                                                .build()
                                        )
                                        .addVariable(
                                            TemplateCreateParams.Definition.Body.MultiChannel
                                                .Variable
                                                .builder()
                                                .name("company")
                                                .props(
                                                    TemplateCreateParams.Definition.Body
                                                        .MultiChannel
                                                        .Variable
                                                        .Props
                                                        .builder()
                                                        .mediaType("x")
                                                        .sample("SentDM")
                                                        .url("x")
                                                        .variableType("text")
                                                        .alt(null)
                                                        .regex(null)
                                                        .shortUrl(null)
                                                        .build()
                                                )
                                                .type("variable")
                                                .id(1)
                                                .build()
                                        )
                                        .build()
                                )
                                .rcs(
                                    TemplateCreateParams.Definition.Body.Rcs.builder()
                                        .template("template")
                                        .type("type")
                                        .addVariable(
                                            TemplateCreateParams.Definition.Body.Rcs.Variable
                                                .builder()
                                                .name("x")
                                                .props(
                                                    TemplateCreateParams.Definition.Body.Rcs
                                                        .Variable
                                                        .Props
                                                        .builder()
                                                        .mediaType("x")
                                                        .sample("x")
                                                        .url("x")
                                                        .variableType("x")
                                                        .alt("alt")
                                                        .regex("regex")
                                                        .shortUrl("shortUrl")
                                                        .build()
                                                )
                                                .type("x")
                                                .id(0)
                                                .build()
                                        )
                                        .build()
                                )
                                .sms(
                                    TemplateCreateParams.Definition.Body.Sms.builder()
                                        .template("template")
                                        .type("type")
                                        .addVariable(
                                            TemplateCreateParams.Definition.Body.Sms.Variable
                                                .builder()
                                                .name("x")
                                                .props(
                                                    TemplateCreateParams.Definition.Body.Sms
                                                        .Variable
                                                        .Props
                                                        .builder()
                                                        .mediaType("x")
                                                        .sample("x")
                                                        .url("x")
                                                        .variableType("x")
                                                        .alt("alt")
                                                        .regex("regex")
                                                        .shortUrl("shortUrl")
                                                        .build()
                                                )
                                                .type("x")
                                                .id(0)
                                                .build()
                                        )
                                        .build()
                                )
                                .whatsapp(
                                    TemplateCreateParams.Definition.Body.Whatsapp.builder()
                                        .template("template")
                                        .type("type")
                                        .addVariable(
                                            TemplateCreateParams.Definition.Body.Whatsapp.Variable
                                                .builder()
                                                .name("x")
                                                .props(
                                                    TemplateCreateParams.Definition.Body.Whatsapp
                                                        .Variable
                                                        .Props
                                                        .builder()
                                                        .mediaType("x")
                                                        .sample("x")
                                                        .url("x")
                                                        .variableType("x")
                                                        .alt("alt")
                                                        .regex("regex")
                                                        .shortUrl("shortUrl")
                                                        .build()
                                                )
                                                .type("x")
                                                .id(0)
                                                .build()
                                        )
                                        .build()
                                )
                                .build()
                        )
                        .authenticationConfig(
                            TemplateCreateParams.Definition.AuthenticationConfig.builder()
                                .addSecurityRecommendation(true)
                                .codeExpirationMinutes(0)
                                .build()
                        )
                        .addButton(
                            TemplateCreateParams.Definition.Button.builder()
                                .props(
                                    TemplateCreateParams.Definition.Button.Props.builder()
                                        .activeFor(1)
                                        .countryCode("x")
                                        .offerCode("x")
                                        .phoneNumber("x")
                                        .quickReplyType("x")
                                        .text("text")
                                        .url("x")
                                        .urlType("x")
                                        .autofillText("autofillText")
                                        .otpType("otpType")
                                        .packageName("packageName")
                                        .signatureHash("signatureHash")
                                        .build()
                                )
                                .type("x")
                                .id(0)
                                .build()
                        )
                        .definitionVersion("1.0")
                        .footer(
                            TemplateCreateParams.Definition.Footer.builder()
                                .template("template")
                                .type("type")
                                .addVariable(
                                    TemplateCreateParams.Definition.Footer.Variable.builder()
                                        .name("x")
                                        .props(
                                            TemplateCreateParams.Definition.Footer.Variable.Props
                                                .builder()
                                                .mediaType("x")
                                                .sample("x")
                                                .url("x")
                                                .variableType("x")
                                                .alt("alt")
                                                .regex("regex")
                                                .shortUrl("shortUrl")
                                                .build()
                                        )
                                        .type("x")
                                        .id(0)
                                        .build()
                                )
                                .build()
                        )
                        .header(
                            TemplateCreateParams.Definition.Header.builder()
                                .template("template")
                                .type("type")
                                .addVariable(
                                    TemplateCreateParams.Definition.Header.Variable.builder()
                                        .name("x")
                                        .props(
                                            TemplateCreateParams.Definition.Header.Variable.Props
                                                .builder()
                                                .mediaType("x")
                                                .sample("x")
                                                .url("x")
                                                .variableType("x")
                                                .alt("alt")
                                                .regex("regex")
                                                .shortUrl("shortUrl")
                                                .build()
                                        )
                                        .type("x")
                                        .id(0)
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .language("en_US")
                .sandbox(false)
                .submitForReview(false)
                .build()

        val body = params._body()

        assertThat(body.category()).contains("MARKETING")
        assertThat(body.creationSource()).isEmpty
        assertThat(body.definition())
            .contains(
                TemplateCreateParams.Definition.builder()
                    .body(
                        TemplateCreateParams.Definition.Body.builder()
                            .multiChannel(
                                TemplateCreateParams.Definition.Body.MultiChannel.builder()
                                    .template("Hello {{0:variable}}! Welcome to {{1:variable}}.")
                                    .type(null)
                                    .addVariable(
                                        TemplateCreateParams.Definition.Body.MultiChannel.Variable
                                            .builder()
                                            .name("name")
                                            .props(
                                                TemplateCreateParams.Definition.Body.MultiChannel
                                                    .Variable
                                                    .Props
                                                    .builder()
                                                    .mediaType("x")
                                                    .sample("John")
                                                    .url("x")
                                                    .variableType("text")
                                                    .alt(null)
                                                    .regex(null)
                                                    .shortUrl(null)
                                                    .build()
                                            )
                                            .type("variable")
                                            .id(0)
                                            .build()
                                    )
                                    .addVariable(
                                        TemplateCreateParams.Definition.Body.MultiChannel.Variable
                                            .builder()
                                            .name("company")
                                            .props(
                                                TemplateCreateParams.Definition.Body.MultiChannel
                                                    .Variable
                                                    .Props
                                                    .builder()
                                                    .mediaType("x")
                                                    .sample("SentDM")
                                                    .url("x")
                                                    .variableType("text")
                                                    .alt(null)
                                                    .regex(null)
                                                    .shortUrl(null)
                                                    .build()
                                            )
                                            .type("variable")
                                            .id(1)
                                            .build()
                                    )
                                    .build()
                            )
                            .rcs(
                                TemplateCreateParams.Definition.Body.Rcs.builder()
                                    .template("template")
                                    .type("type")
                                    .addVariable(
                                        TemplateCreateParams.Definition.Body.Rcs.Variable.builder()
                                            .name("x")
                                            .props(
                                                TemplateCreateParams.Definition.Body.Rcs.Variable
                                                    .Props
                                                    .builder()
                                                    .mediaType("x")
                                                    .sample("x")
                                                    .url("x")
                                                    .variableType("x")
                                                    .alt("alt")
                                                    .regex("regex")
                                                    .shortUrl("shortUrl")
                                                    .build()
                                            )
                                            .type("x")
                                            .id(0)
                                            .build()
                                    )
                                    .build()
                            )
                            .sms(
                                TemplateCreateParams.Definition.Body.Sms.builder()
                                    .template("template")
                                    .type("type")
                                    .addVariable(
                                        TemplateCreateParams.Definition.Body.Sms.Variable.builder()
                                            .name("x")
                                            .props(
                                                TemplateCreateParams.Definition.Body.Sms.Variable
                                                    .Props
                                                    .builder()
                                                    .mediaType("x")
                                                    .sample("x")
                                                    .url("x")
                                                    .variableType("x")
                                                    .alt("alt")
                                                    .regex("regex")
                                                    .shortUrl("shortUrl")
                                                    .build()
                                            )
                                            .type("x")
                                            .id(0)
                                            .build()
                                    )
                                    .build()
                            )
                            .whatsapp(
                                TemplateCreateParams.Definition.Body.Whatsapp.builder()
                                    .template("template")
                                    .type("type")
                                    .addVariable(
                                        TemplateCreateParams.Definition.Body.Whatsapp.Variable
                                            .builder()
                                            .name("x")
                                            .props(
                                                TemplateCreateParams.Definition.Body.Whatsapp
                                                    .Variable
                                                    .Props
                                                    .builder()
                                                    .mediaType("x")
                                                    .sample("x")
                                                    .url("x")
                                                    .variableType("x")
                                                    .alt("alt")
                                                    .regex("regex")
                                                    .shortUrl("shortUrl")
                                                    .build()
                                            )
                                            .type("x")
                                            .id(0)
                                            .build()
                                    )
                                    .build()
                            )
                            .build()
                    )
                    .authenticationConfig(
                        TemplateCreateParams.Definition.AuthenticationConfig.builder()
                            .addSecurityRecommendation(true)
                            .codeExpirationMinutes(0)
                            .build()
                    )
                    .addButton(
                        TemplateCreateParams.Definition.Button.builder()
                            .props(
                                TemplateCreateParams.Definition.Button.Props.builder()
                                    .activeFor(1)
                                    .countryCode("x")
                                    .offerCode("x")
                                    .phoneNumber("x")
                                    .quickReplyType("x")
                                    .text("text")
                                    .url("x")
                                    .urlType("x")
                                    .autofillText("autofillText")
                                    .otpType("otpType")
                                    .packageName("packageName")
                                    .signatureHash("signatureHash")
                                    .build()
                            )
                            .type("x")
                            .id(0)
                            .build()
                    )
                    .definitionVersion("1.0")
                    .footer(
                        TemplateCreateParams.Definition.Footer.builder()
                            .template("template")
                            .type("type")
                            .addVariable(
                                TemplateCreateParams.Definition.Footer.Variable.builder()
                                    .name("x")
                                    .props(
                                        TemplateCreateParams.Definition.Footer.Variable.Props
                                            .builder()
                                            .mediaType("x")
                                            .sample("x")
                                            .url("x")
                                            .variableType("x")
                                            .alt("alt")
                                            .regex("regex")
                                            .shortUrl("shortUrl")
                                            .build()
                                    )
                                    .type("x")
                                    .id(0)
                                    .build()
                            )
                            .build()
                    )
                    .header(
                        TemplateCreateParams.Definition.Header.builder()
                            .template("template")
                            .type("type")
                            .addVariable(
                                TemplateCreateParams.Definition.Header.Variable.builder()
                                    .name("x")
                                    .props(
                                        TemplateCreateParams.Definition.Header.Variable.Props
                                            .builder()
                                            .mediaType("x")
                                            .sample("x")
                                            .url("x")
                                            .variableType("x")
                                            .alt("alt")
                                            .regex("regex")
                                            .shortUrl("shortUrl")
                                            .build()
                                    )
                                    .type("x")
                                    .id(0)
                                    .build()
                            )
                            .build()
                    )
                    .build()
            )
        assertThat(body.language()).contains("en_US")
        assertThat(body.sandbox()).contains(false)
        assertThat(body.submitForReview()).contains(false)
    }

    @Test
    fun bodyWithoutOptionalFields() {
        val params = TemplateCreateParams.builder().build()

        val body = params._body()
    }
}
