// File generated from our OpenAPI spec by Stainless.

package com.sent_dm.api.models.brands.campaigns

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.sent_dm.api.core.jsonMapper
import java.time.OffsetDateTime
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class TcrCampaignWithUseCasesTest {

    @Test
    fun create() {
        val tcrCampaignWithUseCases =
            TcrCampaignWithUseCases.builder()
                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .billedDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .brandId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .cost(0.0)
                .cspId("cspId")
                .customerId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .description("description")
                .helpKeywords("helpKeywords")
                .helpMessage("helpMessage")
                .kycSubmissionFormId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .messageFlow("messageFlow")
                .name("name")
                .optinKeywords("optinKeywords")
                .optinMessage("optinMessage")
                .optoutKeywords("optoutKeywords")
                .optoutMessage("optoutMessage")
                .privacyPolicyLink("privacyPolicyLink")
                .resellerId("resellerId")
                .sharingStatus(TcrCampaignWithUseCases.SharingStatus.PENDING)
                .status(TcrCampaignWithUseCases.Status.SENT_CREATED)
                .submittedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .submittedToTcr(true)
                .tcrCampaignId("tcrCampaignId")
                .tcrSyncError("tcrSyncError")
                .telnyxCampaignId("telnyxCampaignId")
                .termsAndConditionsLink("termsAndConditionsLink")
                .type("type")
                .upstreamCnpId("upstreamCnpId")
                .addUseCase(
                    TcrCampaignWithUseCases.UseCase.builder()
                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .campaignId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .customerId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .messagingUseCaseUs(MessagingUseCaseUs.MARKETING)
                        .addSampleMessage("string")
                        .build()
                )
                .build()

        assertThat(tcrCampaignWithUseCases.id()).contains("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(tcrCampaignWithUseCases.createdAt())
            .contains(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(tcrCampaignWithUseCases.updatedAt())
            .contains(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(tcrCampaignWithUseCases.billedDate())
            .contains(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(tcrCampaignWithUseCases.brandId())
            .contains("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(tcrCampaignWithUseCases.cost()).contains(0.0)
        assertThat(tcrCampaignWithUseCases.cspId()).contains("cspId")
        assertThat(tcrCampaignWithUseCases.customerId())
            .contains("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(tcrCampaignWithUseCases.description()).contains("description")
        assertThat(tcrCampaignWithUseCases.helpKeywords()).contains("helpKeywords")
        assertThat(tcrCampaignWithUseCases.helpMessage()).contains("helpMessage")
        assertThat(tcrCampaignWithUseCases.kycSubmissionFormId())
            .contains("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(tcrCampaignWithUseCases.messageFlow()).contains("messageFlow")
        assertThat(tcrCampaignWithUseCases.name()).contains("name")
        assertThat(tcrCampaignWithUseCases.optinKeywords()).contains("optinKeywords")
        assertThat(tcrCampaignWithUseCases.optinMessage()).contains("optinMessage")
        assertThat(tcrCampaignWithUseCases.optoutKeywords()).contains("optoutKeywords")
        assertThat(tcrCampaignWithUseCases.optoutMessage()).contains("optoutMessage")
        assertThat(tcrCampaignWithUseCases.privacyPolicyLink()).contains("privacyPolicyLink")
        assertThat(tcrCampaignWithUseCases.resellerId()).contains("resellerId")
        assertThat(tcrCampaignWithUseCases.sharingStatus())
            .contains(TcrCampaignWithUseCases.SharingStatus.PENDING)
        assertThat(tcrCampaignWithUseCases.status())
            .contains(TcrCampaignWithUseCases.Status.SENT_CREATED)
        assertThat(tcrCampaignWithUseCases.submittedAt())
            .contains(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(tcrCampaignWithUseCases.submittedToTcr()).contains(true)
        assertThat(tcrCampaignWithUseCases.tcrCampaignId()).contains("tcrCampaignId")
        assertThat(tcrCampaignWithUseCases.tcrSyncError()).contains("tcrSyncError")
        assertThat(tcrCampaignWithUseCases.telnyxCampaignId()).contains("telnyxCampaignId")
        assertThat(tcrCampaignWithUseCases.termsAndConditionsLink())
            .contains("termsAndConditionsLink")
        assertThat(tcrCampaignWithUseCases.type()).contains("type")
        assertThat(tcrCampaignWithUseCases.upstreamCnpId()).contains("upstreamCnpId")
        assertThat(tcrCampaignWithUseCases.useCases().getOrNull())
            .containsExactly(
                TcrCampaignWithUseCases.UseCase.builder()
                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .campaignId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .customerId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .messagingUseCaseUs(MessagingUseCaseUs.MARKETING)
                    .addSampleMessage("string")
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val tcrCampaignWithUseCases =
            TcrCampaignWithUseCases.builder()
                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .billedDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .brandId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .cost(0.0)
                .cspId("cspId")
                .customerId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .description("description")
                .helpKeywords("helpKeywords")
                .helpMessage("helpMessage")
                .kycSubmissionFormId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .messageFlow("messageFlow")
                .name("name")
                .optinKeywords("optinKeywords")
                .optinMessage("optinMessage")
                .optoutKeywords("optoutKeywords")
                .optoutMessage("optoutMessage")
                .privacyPolicyLink("privacyPolicyLink")
                .resellerId("resellerId")
                .sharingStatus(TcrCampaignWithUseCases.SharingStatus.PENDING)
                .status(TcrCampaignWithUseCases.Status.SENT_CREATED)
                .submittedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .submittedToTcr(true)
                .tcrCampaignId("tcrCampaignId")
                .tcrSyncError("tcrSyncError")
                .telnyxCampaignId("telnyxCampaignId")
                .termsAndConditionsLink("termsAndConditionsLink")
                .type("type")
                .upstreamCnpId("upstreamCnpId")
                .addUseCase(
                    TcrCampaignWithUseCases.UseCase.builder()
                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .campaignId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .customerId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .messagingUseCaseUs(MessagingUseCaseUs.MARKETING)
                        .addSampleMessage("string")
                        .build()
                )
                .build()

        val roundtrippedTcrCampaignWithUseCases =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(tcrCampaignWithUseCases),
                jacksonTypeRef<TcrCampaignWithUseCases>(),
            )

        assertThat(roundtrippedTcrCampaignWithUseCases).isEqualTo(tcrCampaignWithUseCases)
    }
}
