// File generated from our OpenAPI spec by Stainless.

package dm.sent.models.profiles

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import dm.sent.core.JsonValue
import dm.sent.core.jsonMapper
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class ProfileUpdateResponseTest {

    @Test
    fun create() {
        val profileUpdateResponse =
            ProfileUpdateResponse.builder()
                .data(
                    ProfileUpdateResponse.Data.builder()
                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .allowContactSharing(true)
                        .allowNumberChangeDuringOnboarding(true)
                        .allowTemplateSharing(true)
                        .billingContact(
                            ProfileUpdateResponse.Data.BillingContact.builder()
                                .address("address")
                                .email("email")
                                .name("name")
                                .phone("phone")
                                .build()
                        )
                        .billingModel("billing_model")
                        .brand(
                            ProfileUpdateResponse.Data.Brand.builder()
                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .business(
                                    ProfileUpdateResponse.Data.Brand.Business.builder()
                                        .city("city")
                                        .country("country")
                                        .countryOfRegistration("country_of_registration")
                                        .entityType("entity_type")
                                        .legalName("legal_name")
                                        .postalCode("postal_code")
                                        .state("state")
                                        .street("street")
                                        .taxId("tax_id")
                                        .taxIdType("tax_id_type")
                                        .url("url")
                                        .build()
                                )
                                .compliance(
                                    ProfileUpdateResponse.Data.Brand.Compliance.builder()
                                        .brandRelationship(
                                            ProfileUpdateResponse.Data.Brand.Compliance
                                                .BrandRelationship
                                                .BASIC_ACCOUNT
                                        )
                                        .addDestinationCountry(
                                            ProfileUpdateResponse.Data.Brand.Compliance
                                                .DestinationCountry
                                                .builder()
                                                .id("id")
                                                .isMain(true)
                                                .build()
                                        )
                                        .expectedMessagingVolume("expected_messaging_volume")
                                        .isTcrApplication(true)
                                        .notes("notes")
                                        .phoneNumberPrefix("phone_number_prefix")
                                        .primaryUseCase("primary_use_case")
                                        .vertical(
                                            ProfileUpdateResponse.Data.Brand.Compliance.Vertical
                                                .PROFESSIONAL
                                        )
                                        .build()
                                )
                                .contact(
                                    ProfileUpdateResponse.Data.Brand.Contact.builder()
                                        .businessName("business_name")
                                        .email("email")
                                        .name("name")
                                        .phone("phone")
                                        .phoneCountryCode("phone_country_code")
                                        .role("role")
                                        .build()
                                )
                                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .cspId("csp_id")
                                .identityStatus(
                                    ProfileUpdateResponse.Data.Brand.IdentityStatus.SELF_DECLARED
                                )
                                .isInherited(true)
                                .status(ProfileUpdateResponse.Data.Brand.Status.ACTIVE)
                                .submittedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .submittedToTcr(true)
                                .tcrBrandId("tcr_brand_id")
                                .universalEin("universal_ein")
                                .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .build()
                        )
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .description("description")
                        .email("email")
                        .icon("icon")
                        .inheritContacts(true)
                        .inheritTcrBrand(true)
                        .inheritTcrCampaign(true)
                        .inheritTemplates(true)
                        .name("name")
                        .organizationId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .sendingPhoneNumber("sending_phone_number")
                        .sendingPhoneNumberProfileId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .sendingWhatsappNumberProfileId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .shortName("short_name")
                        .status("status")
                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .wabaId("waba_id")
                        .whatsappPhoneNumber("whatsapp_phone_number")
                        .build()
                )
                .error(
                    ProfileUpdateResponse.Error.builder()
                        .code("code")
                        .details(
                            ProfileUpdateResponse.Error.Details.builder()
                                .putAdditionalProperty("foo", JsonValue.from(listOf("string")))
                                .build()
                        )
                        .docUrl("doc_url")
                        .message("message")
                        .build()
                )
                .meta(
                    ProfileUpdateResponse.Meta.builder()
                        .requestId("request_id")
                        .timestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .version("version")
                        .build()
                )
                .success(true)
                .build()

        assertThat(profileUpdateResponse.data())
            .contains(
                ProfileUpdateResponse.Data.builder()
                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .allowContactSharing(true)
                    .allowNumberChangeDuringOnboarding(true)
                    .allowTemplateSharing(true)
                    .billingContact(
                        ProfileUpdateResponse.Data.BillingContact.builder()
                            .address("address")
                            .email("email")
                            .name("name")
                            .phone("phone")
                            .build()
                    )
                    .billingModel("billing_model")
                    .brand(
                        ProfileUpdateResponse.Data.Brand.builder()
                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .business(
                                ProfileUpdateResponse.Data.Brand.Business.builder()
                                    .city("city")
                                    .country("country")
                                    .countryOfRegistration("country_of_registration")
                                    .entityType("entity_type")
                                    .legalName("legal_name")
                                    .postalCode("postal_code")
                                    .state("state")
                                    .street("street")
                                    .taxId("tax_id")
                                    .taxIdType("tax_id_type")
                                    .url("url")
                                    .build()
                            )
                            .compliance(
                                ProfileUpdateResponse.Data.Brand.Compliance.builder()
                                    .brandRelationship(
                                        ProfileUpdateResponse.Data.Brand.Compliance
                                            .BrandRelationship
                                            .BASIC_ACCOUNT
                                    )
                                    .addDestinationCountry(
                                        ProfileUpdateResponse.Data.Brand.Compliance
                                            .DestinationCountry
                                            .builder()
                                            .id("id")
                                            .isMain(true)
                                            .build()
                                    )
                                    .expectedMessagingVolume("expected_messaging_volume")
                                    .isTcrApplication(true)
                                    .notes("notes")
                                    .phoneNumberPrefix("phone_number_prefix")
                                    .primaryUseCase("primary_use_case")
                                    .vertical(
                                        ProfileUpdateResponse.Data.Brand.Compliance.Vertical
                                            .PROFESSIONAL
                                    )
                                    .build()
                            )
                            .contact(
                                ProfileUpdateResponse.Data.Brand.Contact.builder()
                                    .businessName("business_name")
                                    .email("email")
                                    .name("name")
                                    .phone("phone")
                                    .phoneCountryCode("phone_country_code")
                                    .role("role")
                                    .build()
                            )
                            .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .cspId("csp_id")
                            .identityStatus(
                                ProfileUpdateResponse.Data.Brand.IdentityStatus.SELF_DECLARED
                            )
                            .isInherited(true)
                            .status(ProfileUpdateResponse.Data.Brand.Status.ACTIVE)
                            .submittedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .submittedToTcr(true)
                            .tcrBrandId("tcr_brand_id")
                            .universalEin("universal_ein")
                            .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .build()
                    )
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .description("description")
                    .email("email")
                    .icon("icon")
                    .inheritContacts(true)
                    .inheritTcrBrand(true)
                    .inheritTcrCampaign(true)
                    .inheritTemplates(true)
                    .name("name")
                    .organizationId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .sendingPhoneNumber("sending_phone_number")
                    .sendingPhoneNumberProfileId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .sendingWhatsappNumberProfileId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .shortName("short_name")
                    .status("status")
                    .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .wabaId("waba_id")
                    .whatsappPhoneNumber("whatsapp_phone_number")
                    .build()
            )
        assertThat(profileUpdateResponse.error())
            .contains(
                ProfileUpdateResponse.Error.builder()
                    .code("code")
                    .details(
                        ProfileUpdateResponse.Error.Details.builder()
                            .putAdditionalProperty("foo", JsonValue.from(listOf("string")))
                            .build()
                    )
                    .docUrl("doc_url")
                    .message("message")
                    .build()
            )
        assertThat(profileUpdateResponse.meta())
            .contains(
                ProfileUpdateResponse.Meta.builder()
                    .requestId("request_id")
                    .timestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .version("version")
                    .build()
            )
        assertThat(profileUpdateResponse.success()).contains(true)
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val profileUpdateResponse =
            ProfileUpdateResponse.builder()
                .data(
                    ProfileUpdateResponse.Data.builder()
                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .allowContactSharing(true)
                        .allowNumberChangeDuringOnboarding(true)
                        .allowTemplateSharing(true)
                        .billingContact(
                            ProfileUpdateResponse.Data.BillingContact.builder()
                                .address("address")
                                .email("email")
                                .name("name")
                                .phone("phone")
                                .build()
                        )
                        .billingModel("billing_model")
                        .brand(
                            ProfileUpdateResponse.Data.Brand.builder()
                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .business(
                                    ProfileUpdateResponse.Data.Brand.Business.builder()
                                        .city("city")
                                        .country("country")
                                        .countryOfRegistration("country_of_registration")
                                        .entityType("entity_type")
                                        .legalName("legal_name")
                                        .postalCode("postal_code")
                                        .state("state")
                                        .street("street")
                                        .taxId("tax_id")
                                        .taxIdType("tax_id_type")
                                        .url("url")
                                        .build()
                                )
                                .compliance(
                                    ProfileUpdateResponse.Data.Brand.Compliance.builder()
                                        .brandRelationship(
                                            ProfileUpdateResponse.Data.Brand.Compliance
                                                .BrandRelationship
                                                .BASIC_ACCOUNT
                                        )
                                        .addDestinationCountry(
                                            ProfileUpdateResponse.Data.Brand.Compliance
                                                .DestinationCountry
                                                .builder()
                                                .id("id")
                                                .isMain(true)
                                                .build()
                                        )
                                        .expectedMessagingVolume("expected_messaging_volume")
                                        .isTcrApplication(true)
                                        .notes("notes")
                                        .phoneNumberPrefix("phone_number_prefix")
                                        .primaryUseCase("primary_use_case")
                                        .vertical(
                                            ProfileUpdateResponse.Data.Brand.Compliance.Vertical
                                                .PROFESSIONAL
                                        )
                                        .build()
                                )
                                .contact(
                                    ProfileUpdateResponse.Data.Brand.Contact.builder()
                                        .businessName("business_name")
                                        .email("email")
                                        .name("name")
                                        .phone("phone")
                                        .phoneCountryCode("phone_country_code")
                                        .role("role")
                                        .build()
                                )
                                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .cspId("csp_id")
                                .identityStatus(
                                    ProfileUpdateResponse.Data.Brand.IdentityStatus.SELF_DECLARED
                                )
                                .isInherited(true)
                                .status(ProfileUpdateResponse.Data.Brand.Status.ACTIVE)
                                .submittedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .submittedToTcr(true)
                                .tcrBrandId("tcr_brand_id")
                                .universalEin("universal_ein")
                                .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .build()
                        )
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .description("description")
                        .email("email")
                        .icon("icon")
                        .inheritContacts(true)
                        .inheritTcrBrand(true)
                        .inheritTcrCampaign(true)
                        .inheritTemplates(true)
                        .name("name")
                        .organizationId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .sendingPhoneNumber("sending_phone_number")
                        .sendingPhoneNumberProfileId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .sendingWhatsappNumberProfileId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .shortName("short_name")
                        .status("status")
                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .wabaId("waba_id")
                        .whatsappPhoneNumber("whatsapp_phone_number")
                        .build()
                )
                .error(
                    ProfileUpdateResponse.Error.builder()
                        .code("code")
                        .details(
                            ProfileUpdateResponse.Error.Details.builder()
                                .putAdditionalProperty("foo", JsonValue.from(listOf("string")))
                                .build()
                        )
                        .docUrl("doc_url")
                        .message("message")
                        .build()
                )
                .meta(
                    ProfileUpdateResponse.Meta.builder()
                        .requestId("request_id")
                        .timestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .version("version")
                        .build()
                )
                .success(true)
                .build()

        val roundtrippedProfileUpdateResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(profileUpdateResponse),
                jacksonTypeRef<ProfileUpdateResponse>(),
            )

        assertThat(roundtrippedProfileUpdateResponse).isEqualTo(profileUpdateResponse)
    }
}
