// File generated from our OpenAPI spec by Stainless.

package dm.sent.models.profiles

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import dm.sent.core.JsonValue
import dm.sent.core.jsonMapper
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class ProfileListResponseTest {

    @Test
    fun create() {
        val profileListResponse =
            ProfileListResponse.builder()
                .data(
                    ProfileListResponse.Data.builder()
                        .addProfile(
                            ProfileListResponse.Data.Profile.builder()
                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .allowContactSharing(true)
                                .allowNumberChangeDuringOnboarding(true)
                                .allowTemplateSharing(true)
                                .billingContact(
                                    ProfileListResponse.Data.Profile.BillingContact.builder()
                                        .address("address")
                                        .email("email")
                                        .name("name")
                                        .phone("phone")
                                        .build()
                                )
                                .billingModel("billing_model")
                                .brand(
                                    ProfileListResponse.Data.Profile.Brand.builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .business(
                                            ProfileListResponse.Data.Profile.Brand.Business
                                                .builder()
                                                .city("city")
                                                .country("country")
                                                .countryOfRegistration("country_of_registration")
                                                .entityType("entity_type")
                                                .legalName("legal_name")
                                                .postalCode("postal_code")
                                                .state("state")
                                                .street("street")
                                                .taxId("tax_id")
                                                .taxIdType("tax_id_type")
                                                .url("url")
                                                .build()
                                        )
                                        .compliance(
                                            ProfileListResponse.Data.Profile.Brand.Compliance
                                                .builder()
                                                .brandRelationship(
                                                    ProfileListResponse.Data.Profile.Brand
                                                        .Compliance
                                                        .BrandRelationship
                                                        .BASIC_ACCOUNT
                                                )
                                                .addDestinationCountry(
                                                    ProfileListResponse.Data.Profile.Brand
                                                        .Compliance
                                                        .DestinationCountry
                                                        .builder()
                                                        .id("id")
                                                        .isMain(true)
                                                        .build()
                                                )
                                                .expectedMessagingVolume(
                                                    "expected_messaging_volume"
                                                )
                                                .isTcrApplication(true)
                                                .notes("notes")
                                                .phoneNumberPrefix("phone_number_prefix")
                                                .primaryUseCase("primary_use_case")
                                                .vertical(
                                                    ProfileListResponse.Data.Profile.Brand
                                                        .Compliance
                                                        .Vertical
                                                        .PROFESSIONAL
                                                )
                                                .build()
                                        )
                                        .contact(
                                            ProfileListResponse.Data.Profile.Brand.Contact.builder()
                                                .businessName("business_name")
                                                .email("email")
                                                .name("name")
                                                .phone("phone")
                                                .phoneCountryCode("phone_country_code")
                                                .role("role")
                                                .build()
                                        )
                                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .cspId("csp_id")
                                        .identityStatus(
                                            ProfileListResponse.Data.Profile.Brand.IdentityStatus
                                                .SELF_DECLARED
                                        )
                                        .isInherited(true)
                                        .status(
                                            ProfileListResponse.Data.Profile.Brand.Status.ACTIVE
                                        )
                                        .submittedAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .submittedToTcr(true)
                                        .tcrBrandId("tcr_brand_id")
                                        .universalEin("universal_ein")
                                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .build()
                                )
                                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .description("description")
                                .email("email")
                                .icon("icon")
                                .inheritContacts(true)
                                .inheritTcrBrand(true)
                                .inheritTcrCampaign(true)
                                .inheritTemplates(true)
                                .name("name")
                                .organizationId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .sendingPhoneNumber("sending_phone_number")
                                .sendingPhoneNumberProfileId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .sendingWhatsappNumberProfileId(
                                    "182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"
                                )
                                .shortName("short_name")
                                .status("status")
                                .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .wabaId("waba_id")
                                .whatsappPhoneNumber("whatsapp_phone_number")
                                .build()
                        )
                        .build()
                )
                .error(
                    ProfileListResponse.Error.builder()
                        .code("code")
                        .details(
                            ProfileListResponse.Error.Details.builder()
                                .putAdditionalProperty("foo", JsonValue.from(listOf("string")))
                                .build()
                        )
                        .docUrl("doc_url")
                        .message("message")
                        .build()
                )
                .meta(
                    ProfileListResponse.Meta.builder()
                        .requestId("request_id")
                        .timestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .version("version")
                        .build()
                )
                .success(true)
                .build()

        assertThat(profileListResponse.data())
            .contains(
                ProfileListResponse.Data.builder()
                    .addProfile(
                        ProfileListResponse.Data.Profile.builder()
                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .allowContactSharing(true)
                            .allowNumberChangeDuringOnboarding(true)
                            .allowTemplateSharing(true)
                            .billingContact(
                                ProfileListResponse.Data.Profile.BillingContact.builder()
                                    .address("address")
                                    .email("email")
                                    .name("name")
                                    .phone("phone")
                                    .build()
                            )
                            .billingModel("billing_model")
                            .brand(
                                ProfileListResponse.Data.Profile.Brand.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .business(
                                        ProfileListResponse.Data.Profile.Brand.Business.builder()
                                            .city("city")
                                            .country("country")
                                            .countryOfRegistration("country_of_registration")
                                            .entityType("entity_type")
                                            .legalName("legal_name")
                                            .postalCode("postal_code")
                                            .state("state")
                                            .street("street")
                                            .taxId("tax_id")
                                            .taxIdType("tax_id_type")
                                            .url("url")
                                            .build()
                                    )
                                    .compliance(
                                        ProfileListResponse.Data.Profile.Brand.Compliance.builder()
                                            .brandRelationship(
                                                ProfileListResponse.Data.Profile.Brand.Compliance
                                                    .BrandRelationship
                                                    .BASIC_ACCOUNT
                                            )
                                            .addDestinationCountry(
                                                ProfileListResponse.Data.Profile.Brand.Compliance
                                                    .DestinationCountry
                                                    .builder()
                                                    .id("id")
                                                    .isMain(true)
                                                    .build()
                                            )
                                            .expectedMessagingVolume("expected_messaging_volume")
                                            .isTcrApplication(true)
                                            .notes("notes")
                                            .phoneNumberPrefix("phone_number_prefix")
                                            .primaryUseCase("primary_use_case")
                                            .vertical(
                                                ProfileListResponse.Data.Profile.Brand.Compliance
                                                    .Vertical
                                                    .PROFESSIONAL
                                            )
                                            .build()
                                    )
                                    .contact(
                                        ProfileListResponse.Data.Profile.Brand.Contact.builder()
                                            .businessName("business_name")
                                            .email("email")
                                            .name("name")
                                            .phone("phone")
                                            .phoneCountryCode("phone_country_code")
                                            .role("role")
                                            .build()
                                    )
                                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .cspId("csp_id")
                                    .identityStatus(
                                        ProfileListResponse.Data.Profile.Brand.IdentityStatus
                                            .SELF_DECLARED
                                    )
                                    .isInherited(true)
                                    .status(ProfileListResponse.Data.Profile.Brand.Status.ACTIVE)
                                    .submittedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .submittedToTcr(true)
                                    .tcrBrandId("tcr_brand_id")
                                    .universalEin("universal_ein")
                                    .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .build()
                            )
                            .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .description("description")
                            .email("email")
                            .icon("icon")
                            .inheritContacts(true)
                            .inheritTcrBrand(true)
                            .inheritTcrCampaign(true)
                            .inheritTemplates(true)
                            .name("name")
                            .organizationId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .sendingPhoneNumber("sending_phone_number")
                            .sendingPhoneNumberProfileId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .sendingWhatsappNumberProfileId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .shortName("short_name")
                            .status("status")
                            .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .wabaId("waba_id")
                            .whatsappPhoneNumber("whatsapp_phone_number")
                            .build()
                    )
                    .build()
            )
        assertThat(profileListResponse.error())
            .contains(
                ProfileListResponse.Error.builder()
                    .code("code")
                    .details(
                        ProfileListResponse.Error.Details.builder()
                            .putAdditionalProperty("foo", JsonValue.from(listOf("string")))
                            .build()
                    )
                    .docUrl("doc_url")
                    .message("message")
                    .build()
            )
        assertThat(profileListResponse.meta())
            .contains(
                ProfileListResponse.Meta.builder()
                    .requestId("request_id")
                    .timestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .version("version")
                    .build()
            )
        assertThat(profileListResponse.success()).contains(true)
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val profileListResponse =
            ProfileListResponse.builder()
                .data(
                    ProfileListResponse.Data.builder()
                        .addProfile(
                            ProfileListResponse.Data.Profile.builder()
                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .allowContactSharing(true)
                                .allowNumberChangeDuringOnboarding(true)
                                .allowTemplateSharing(true)
                                .billingContact(
                                    ProfileListResponse.Data.Profile.BillingContact.builder()
                                        .address("address")
                                        .email("email")
                                        .name("name")
                                        .phone("phone")
                                        .build()
                                )
                                .billingModel("billing_model")
                                .brand(
                                    ProfileListResponse.Data.Profile.Brand.builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .business(
                                            ProfileListResponse.Data.Profile.Brand.Business
                                                .builder()
                                                .city("city")
                                                .country("country")
                                                .countryOfRegistration("country_of_registration")
                                                .entityType("entity_type")
                                                .legalName("legal_name")
                                                .postalCode("postal_code")
                                                .state("state")
                                                .street("street")
                                                .taxId("tax_id")
                                                .taxIdType("tax_id_type")
                                                .url("url")
                                                .build()
                                        )
                                        .compliance(
                                            ProfileListResponse.Data.Profile.Brand.Compliance
                                                .builder()
                                                .brandRelationship(
                                                    ProfileListResponse.Data.Profile.Brand
                                                        .Compliance
                                                        .BrandRelationship
                                                        .BASIC_ACCOUNT
                                                )
                                                .addDestinationCountry(
                                                    ProfileListResponse.Data.Profile.Brand
                                                        .Compliance
                                                        .DestinationCountry
                                                        .builder()
                                                        .id("id")
                                                        .isMain(true)
                                                        .build()
                                                )
                                                .expectedMessagingVolume(
                                                    "expected_messaging_volume"
                                                )
                                                .isTcrApplication(true)
                                                .notes("notes")
                                                .phoneNumberPrefix("phone_number_prefix")
                                                .primaryUseCase("primary_use_case")
                                                .vertical(
                                                    ProfileListResponse.Data.Profile.Brand
                                                        .Compliance
                                                        .Vertical
                                                        .PROFESSIONAL
                                                )
                                                .build()
                                        )
                                        .contact(
                                            ProfileListResponse.Data.Profile.Brand.Contact.builder()
                                                .businessName("business_name")
                                                .email("email")
                                                .name("name")
                                                .phone("phone")
                                                .phoneCountryCode("phone_country_code")
                                                .role("role")
                                                .build()
                                        )
                                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .cspId("csp_id")
                                        .identityStatus(
                                            ProfileListResponse.Data.Profile.Brand.IdentityStatus
                                                .SELF_DECLARED
                                        )
                                        .isInherited(true)
                                        .status(
                                            ProfileListResponse.Data.Profile.Brand.Status.ACTIVE
                                        )
                                        .submittedAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .submittedToTcr(true)
                                        .tcrBrandId("tcr_brand_id")
                                        .universalEin("universal_ein")
                                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .build()
                                )
                                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .description("description")
                                .email("email")
                                .icon("icon")
                                .inheritContacts(true)
                                .inheritTcrBrand(true)
                                .inheritTcrCampaign(true)
                                .inheritTemplates(true)
                                .name("name")
                                .organizationId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .sendingPhoneNumber("sending_phone_number")
                                .sendingPhoneNumberProfileId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .sendingWhatsappNumberProfileId(
                                    "182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"
                                )
                                .shortName("short_name")
                                .status("status")
                                .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .wabaId("waba_id")
                                .whatsappPhoneNumber("whatsapp_phone_number")
                                .build()
                        )
                        .build()
                )
                .error(
                    ProfileListResponse.Error.builder()
                        .code("code")
                        .details(
                            ProfileListResponse.Error.Details.builder()
                                .putAdditionalProperty("foo", JsonValue.from(listOf("string")))
                                .build()
                        )
                        .docUrl("doc_url")
                        .message("message")
                        .build()
                )
                .meta(
                    ProfileListResponse.Meta.builder()
                        .requestId("request_id")
                        .timestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .version("version")
                        .build()
                )
                .success(true)
                .build()

        val roundtrippedProfileListResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(profileListResponse),
                jacksonTypeRef<ProfileListResponse>(),
            )

        assertThat(roundtrippedProfileListResponse).isEqualTo(profileListResponse)
    }
}
