// File generated from our OpenAPI spec by Stainless.

package dm.sent.models.me

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import dm.sent.core.JsonValue
import dm.sent.core.jsonMapper
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class MeRetrieveResponseTest {

    @Test
    fun create() {
        val meRetrieveResponse =
            MeRetrieveResponse.builder()
                .data(
                    MeRetrieveResponse.Data.builder()
                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .channels(
                            MeRetrieveResponse.Data.Channels.builder()
                                .rcs(
                                    MeRetrieveResponse.Data.Channels.Rcs.builder()
                                        .configured(true)
                                        .phoneNumber("phone_number")
                                        .build()
                                )
                                .sms(
                                    MeRetrieveResponse.Data.Channels.Sms.builder()
                                        .configured(true)
                                        .phoneNumber("phone_number")
                                        .build()
                                )
                                .whatsapp(
                                    MeRetrieveResponse.Data.Channels.Whatsapp.builder()
                                        .businessName("business_name")
                                        .configured(true)
                                        .phoneNumber("phone_number")
                                        .build()
                                )
                                .build()
                        )
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .description("description")
                        .email("email")
                        .icon("icon")
                        .name("name")
                        .organizationId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .addProfile(
                            MeRetrieveResponse.Data.Profile.builder()
                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .description("description")
                                .icon("icon")
                                .name("name")
                                .role("role")
                                .settings(
                                    MeRetrieveResponse.Data.Profile.Settings.builder()
                                        .allowContactSharing(true)
                                        .allowTemplateSharing(true)
                                        .billingModel("billing_model")
                                        .inheritContacts(true)
                                        .inheritTcrBrand(true)
                                        .inheritTcrCampaign(true)
                                        .inheritTemplates(true)
                                        .build()
                                )
                                .shortName("short_name")
                                .status("status")
                                .build()
                        )
                        .settings(
                            MeRetrieveResponse.Data.Settings.builder()
                                .allowContactSharing(true)
                                .allowTemplateSharing(true)
                                .billingModel("billing_model")
                                .inheritContacts(true)
                                .inheritTcrBrand(true)
                                .inheritTcrCampaign(true)
                                .inheritTemplates(true)
                                .build()
                        )
                        .shortName("short_name")
                        .status("status")
                        .type("type")
                        .build()
                )
                .error(
                    MeRetrieveResponse.Error.builder()
                        .code("code")
                        .details(
                            MeRetrieveResponse.Error.Details.builder()
                                .putAdditionalProperty("foo", JsonValue.from(listOf("string")))
                                .build()
                        )
                        .docUrl("doc_url")
                        .message("message")
                        .build()
                )
                .meta(
                    MeRetrieveResponse.Meta.builder()
                        .requestId("request_id")
                        .timestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .version("version")
                        .build()
                )
                .success(true)
                .build()

        assertThat(meRetrieveResponse.data())
            .contains(
                MeRetrieveResponse.Data.builder()
                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .channels(
                        MeRetrieveResponse.Data.Channels.builder()
                            .rcs(
                                MeRetrieveResponse.Data.Channels.Rcs.builder()
                                    .configured(true)
                                    .phoneNumber("phone_number")
                                    .build()
                            )
                            .sms(
                                MeRetrieveResponse.Data.Channels.Sms.builder()
                                    .configured(true)
                                    .phoneNumber("phone_number")
                                    .build()
                            )
                            .whatsapp(
                                MeRetrieveResponse.Data.Channels.Whatsapp.builder()
                                    .businessName("business_name")
                                    .configured(true)
                                    .phoneNumber("phone_number")
                                    .build()
                            )
                            .build()
                    )
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .description("description")
                    .email("email")
                    .icon("icon")
                    .name("name")
                    .organizationId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .addProfile(
                        MeRetrieveResponse.Data.Profile.builder()
                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .description("description")
                            .icon("icon")
                            .name("name")
                            .role("role")
                            .settings(
                                MeRetrieveResponse.Data.Profile.Settings.builder()
                                    .allowContactSharing(true)
                                    .allowTemplateSharing(true)
                                    .billingModel("billing_model")
                                    .inheritContacts(true)
                                    .inheritTcrBrand(true)
                                    .inheritTcrCampaign(true)
                                    .inheritTemplates(true)
                                    .build()
                            )
                            .shortName("short_name")
                            .status("status")
                            .build()
                    )
                    .settings(
                        MeRetrieveResponse.Data.Settings.builder()
                            .allowContactSharing(true)
                            .allowTemplateSharing(true)
                            .billingModel("billing_model")
                            .inheritContacts(true)
                            .inheritTcrBrand(true)
                            .inheritTcrCampaign(true)
                            .inheritTemplates(true)
                            .build()
                    )
                    .shortName("short_name")
                    .status("status")
                    .type("type")
                    .build()
            )
        assertThat(meRetrieveResponse.error())
            .contains(
                MeRetrieveResponse.Error.builder()
                    .code("code")
                    .details(
                        MeRetrieveResponse.Error.Details.builder()
                            .putAdditionalProperty("foo", JsonValue.from(listOf("string")))
                            .build()
                    )
                    .docUrl("doc_url")
                    .message("message")
                    .build()
            )
        assertThat(meRetrieveResponse.meta())
            .contains(
                MeRetrieveResponse.Meta.builder()
                    .requestId("request_id")
                    .timestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .version("version")
                    .build()
            )
        assertThat(meRetrieveResponse.success()).contains(true)
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val meRetrieveResponse =
            MeRetrieveResponse.builder()
                .data(
                    MeRetrieveResponse.Data.builder()
                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .channels(
                            MeRetrieveResponse.Data.Channels.builder()
                                .rcs(
                                    MeRetrieveResponse.Data.Channels.Rcs.builder()
                                        .configured(true)
                                        .phoneNumber("phone_number")
                                        .build()
                                )
                                .sms(
                                    MeRetrieveResponse.Data.Channels.Sms.builder()
                                        .configured(true)
                                        .phoneNumber("phone_number")
                                        .build()
                                )
                                .whatsapp(
                                    MeRetrieveResponse.Data.Channels.Whatsapp.builder()
                                        .businessName("business_name")
                                        .configured(true)
                                        .phoneNumber("phone_number")
                                        .build()
                                )
                                .build()
                        )
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .description("description")
                        .email("email")
                        .icon("icon")
                        .name("name")
                        .organizationId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .addProfile(
                            MeRetrieveResponse.Data.Profile.builder()
                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .description("description")
                                .icon("icon")
                                .name("name")
                                .role("role")
                                .settings(
                                    MeRetrieveResponse.Data.Profile.Settings.builder()
                                        .allowContactSharing(true)
                                        .allowTemplateSharing(true)
                                        .billingModel("billing_model")
                                        .inheritContacts(true)
                                        .inheritTcrBrand(true)
                                        .inheritTcrCampaign(true)
                                        .inheritTemplates(true)
                                        .build()
                                )
                                .shortName("short_name")
                                .status("status")
                                .build()
                        )
                        .settings(
                            MeRetrieveResponse.Data.Settings.builder()
                                .allowContactSharing(true)
                                .allowTemplateSharing(true)
                                .billingModel("billing_model")
                                .inheritContacts(true)
                                .inheritTcrBrand(true)
                                .inheritTcrCampaign(true)
                                .inheritTemplates(true)
                                .build()
                        )
                        .shortName("short_name")
                        .status("status")
                        .type("type")
                        .build()
                )
                .error(
                    MeRetrieveResponse.Error.builder()
                        .code("code")
                        .details(
                            MeRetrieveResponse.Error.Details.builder()
                                .putAdditionalProperty("foo", JsonValue.from(listOf("string")))
                                .build()
                        )
                        .docUrl("doc_url")
                        .message("message")
                        .build()
                )
                .meta(
                    MeRetrieveResponse.Meta.builder()
                        .requestId("request_id")
                        .timestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .version("version")
                        .build()
                )
                .success(true)
                .build()

        val roundtrippedMeRetrieveResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(meRetrieveResponse),
                jacksonTypeRef<MeRetrieveResponse>(),
            )

        assertThat(roundtrippedMeRetrieveResponse).isEqualTo(meRetrieveResponse)
    }
}
