// File generated from our OpenAPI spec by Stainless.

package dm.sent.services.blocking

import dm.sent.client.okhttp.SentOkHttpClient
import dm.sent.models.templates.TemplateCreateParams
import dm.sent.models.templates.TemplateDeleteParams
import dm.sent.models.templates.TemplateListParams
import dm.sent.models.templates.TemplateRetrieveParams
import dm.sent.models.templates.TemplateUpdateParams
import org.junit.jupiter.api.Disabled
import org.junit.jupiter.api.Test

internal class TemplateServiceTest {

    @Disabled("Mock server tests are disabled")
    @Test
    fun create() {
        val client = SentOkHttpClient.builder().apiKey("My API Key").build()
        val templateService = client.templates()

        val template =
            templateService.create(
                TemplateCreateParams.builder()
                    .idempotencyKey("req_abc123_retry1")
                    .xProfileId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .category("MARKETING")
                    .creationSource(null)
                    .definition(
                        TemplateCreateParams.Definition.builder()
                            .body(
                                TemplateCreateParams.Definition.Body.builder()
                                    .multiChannel(
                                        TemplateCreateParams.Definition.Body.MultiChannel.builder()
                                            .template(
                                                "Hello {{0:variable}}! Welcome to {{1:variable}}."
                                            )
                                            .type(null)
                                            .addVariable(
                                                TemplateCreateParams.Definition.Body.MultiChannel
                                                    .Variable
                                                    .builder()
                                                    .name("name")
                                                    .props(
                                                        TemplateCreateParams.Definition.Body
                                                            .MultiChannel
                                                            .Variable
                                                            .Props
                                                            .builder()
                                                            .mediaType("x")
                                                            .sample("John")
                                                            .url("x")
                                                            .variableType("text")
                                                            .alt(null)
                                                            .regex(null)
                                                            .shortUrl(null)
                                                            .build()
                                                    )
                                                    .type("variable")
                                                    .id(0)
                                                    .build()
                                            )
                                            .addVariable(
                                                TemplateCreateParams.Definition.Body.MultiChannel
                                                    .Variable
                                                    .builder()
                                                    .name("company")
                                                    .props(
                                                        TemplateCreateParams.Definition.Body
                                                            .MultiChannel
                                                            .Variable
                                                            .Props
                                                            .builder()
                                                            .mediaType("x")
                                                            .sample("SentDM")
                                                            .url("x")
                                                            .variableType("text")
                                                            .alt(null)
                                                            .regex(null)
                                                            .shortUrl(null)
                                                            .build()
                                                    )
                                                    .type("variable")
                                                    .id(1)
                                                    .build()
                                            )
                                            .build()
                                    )
                                    .rcs(
                                        TemplateCreateParams.Definition.Body.Rcs.builder()
                                            .template("template")
                                            .type("type")
                                            .addVariable(
                                                TemplateCreateParams.Definition.Body.Rcs.Variable
                                                    .builder()
                                                    .name("x")
                                                    .props(
                                                        TemplateCreateParams.Definition.Body.Rcs
                                                            .Variable
                                                            .Props
                                                            .builder()
                                                            .mediaType("x")
                                                            .sample("x")
                                                            .url("x")
                                                            .variableType("x")
                                                            .alt("alt")
                                                            .regex("regex")
                                                            .shortUrl("shortUrl")
                                                            .build()
                                                    )
                                                    .type("x")
                                                    .id(0)
                                                    .build()
                                            )
                                            .build()
                                    )
                                    .sms(
                                        TemplateCreateParams.Definition.Body.Sms.builder()
                                            .template("template")
                                            .type("type")
                                            .addVariable(
                                                TemplateCreateParams.Definition.Body.Sms.Variable
                                                    .builder()
                                                    .name("x")
                                                    .props(
                                                        TemplateCreateParams.Definition.Body.Sms
                                                            .Variable
                                                            .Props
                                                            .builder()
                                                            .mediaType("x")
                                                            .sample("x")
                                                            .url("x")
                                                            .variableType("x")
                                                            .alt("alt")
                                                            .regex("regex")
                                                            .shortUrl("shortUrl")
                                                            .build()
                                                    )
                                                    .type("x")
                                                    .id(0)
                                                    .build()
                                            )
                                            .build()
                                    )
                                    .whatsapp(
                                        TemplateCreateParams.Definition.Body.Whatsapp.builder()
                                            .template("template")
                                            .type("type")
                                            .addVariable(
                                                TemplateCreateParams.Definition.Body.Whatsapp
                                                    .Variable
                                                    .builder()
                                                    .name("x")
                                                    .props(
                                                        TemplateCreateParams.Definition.Body
                                                            .Whatsapp
                                                            .Variable
                                                            .Props
                                                            .builder()
                                                            .mediaType("x")
                                                            .sample("x")
                                                            .url("x")
                                                            .variableType("x")
                                                            .alt("alt")
                                                            .regex("regex")
                                                            .shortUrl("shortUrl")
                                                            .build()
                                                    )
                                                    .type("x")
                                                    .id(0)
                                                    .build()
                                            )
                                            .build()
                                    )
                                    .build()
                            )
                            .authenticationConfig(
                                TemplateCreateParams.Definition.AuthenticationConfig.builder()
                                    .addSecurityRecommendation(true)
                                    .codeExpirationMinutes(0)
                                    .build()
                            )
                            .addButton(
                                TemplateCreateParams.Definition.Button.builder()
                                    .props(
                                        TemplateCreateParams.Definition.Button.Props.builder()
                                            .activeFor(1)
                                            .countryCode("x")
                                            .offerCode("x")
                                            .phoneNumber("x")
                                            .quickReplyType("x")
                                            .text("text")
                                            .url("x")
                                            .urlType("x")
                                            .autofillText("autofillText")
                                            .otpType("otpType")
                                            .packageName("packageName")
                                            .signatureHash("signatureHash")
                                            .build()
                                    )
                                    .type("x")
                                    .id(0)
                                    .build()
                            )
                            .definitionVersion("1.0")
                            .footer(
                                TemplateCreateParams.Definition.Footer.builder()
                                    .template("template")
                                    .type("type")
                                    .addVariable(
                                        TemplateCreateParams.Definition.Footer.Variable.builder()
                                            .name("x")
                                            .props(
                                                TemplateCreateParams.Definition.Footer.Variable
                                                    .Props
                                                    .builder()
                                                    .mediaType("x")
                                                    .sample("x")
                                                    .url("x")
                                                    .variableType("x")
                                                    .alt("alt")
                                                    .regex("regex")
                                                    .shortUrl("shortUrl")
                                                    .build()
                                            )
                                            .type("x")
                                            .id(0)
                                            .build()
                                    )
                                    .build()
                            )
                            .header(
                                TemplateCreateParams.Definition.Header.builder()
                                    .template("template")
                                    .type("type")
                                    .addVariable(
                                        TemplateCreateParams.Definition.Header.Variable.builder()
                                            .name("x")
                                            .props(
                                                TemplateCreateParams.Definition.Header.Variable
                                                    .Props
                                                    .builder()
                                                    .mediaType("x")
                                                    .sample("x")
                                                    .url("x")
                                                    .variableType("x")
                                                    .alt("alt")
                                                    .regex("regex")
                                                    .shortUrl("shortUrl")
                                                    .build()
                                            )
                                            .type("x")
                                            .id(0)
                                            .build()
                                    )
                                    .build()
                            )
                            .build()
                    )
                    .language("en_US")
                    .sandbox(false)
                    .submitForReview(false)
                    .build()
            )

        template.validate()
    }

    @Disabled("Mock server tests are disabled")
    @Test
    fun retrieve() {
        val client = SentOkHttpClient.builder().apiKey("My API Key").build()
        val templateService = client.templates()

        val template =
            templateService.retrieve(
                TemplateRetrieveParams.builder()
                    .id("7ba7b820-9dad-11d1-80b4-00c04fd430c8")
                    .xProfileId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .build()
            )

        template.validate()
    }

    @Disabled("Mock server tests are disabled")
    @Test
    fun update() {
        val client = SentOkHttpClient.builder().apiKey("My API Key").build()
        val templateService = client.templates()

        val template =
            templateService.update(
                TemplateUpdateParams.builder()
                    .id("7ba7b820-9dad-11d1-80b4-00c04fd430c8")
                    .idempotencyKey("req_abc123_retry1")
                    .xProfileId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .category("MARKETING")
                    .definition(
                        TemplateUpdateParams.Definition.builder()
                            .body(
                                TemplateUpdateParams.Definition.Body.builder()
                                    .multiChannel(
                                        TemplateUpdateParams.Definition.Body.MultiChannel.builder()
                                            .template("template")
                                            .type("type")
                                            .addVariable(
                                                TemplateUpdateParams.Definition.Body.MultiChannel
                                                    .Variable
                                                    .builder()
                                                    .name("x")
                                                    .props(
                                                        TemplateUpdateParams.Definition.Body
                                                            .MultiChannel
                                                            .Variable
                                                            .Props
                                                            .builder()
                                                            .mediaType("x")
                                                            .sample("x")
                                                            .url("x")
                                                            .variableType("x")
                                                            .alt("alt")
                                                            .regex("regex")
                                                            .shortUrl("shortUrl")
                                                            .build()
                                                    )
                                                    .type("x")
                                                    .id(0)
                                                    .build()
                                            )
                                            .build()
                                    )
                                    .rcs(
                                        TemplateUpdateParams.Definition.Body.Rcs.builder()
                                            .template("template")
                                            .type("type")
                                            .addVariable(
                                                TemplateUpdateParams.Definition.Body.Rcs.Variable
                                                    .builder()
                                                    .name("x")
                                                    .props(
                                                        TemplateUpdateParams.Definition.Body.Rcs
                                                            .Variable
                                                            .Props
                                                            .builder()
                                                            .mediaType("x")
                                                            .sample("x")
                                                            .url("x")
                                                            .variableType("x")
                                                            .alt("alt")
                                                            .regex("regex")
                                                            .shortUrl("shortUrl")
                                                            .build()
                                                    )
                                                    .type("x")
                                                    .id(0)
                                                    .build()
                                            )
                                            .build()
                                    )
                                    .sms(
                                        TemplateUpdateParams.Definition.Body.Sms.builder()
                                            .template("template")
                                            .type("type")
                                            .addVariable(
                                                TemplateUpdateParams.Definition.Body.Sms.Variable
                                                    .builder()
                                                    .name("x")
                                                    .props(
                                                        TemplateUpdateParams.Definition.Body.Sms
                                                            .Variable
                                                            .Props
                                                            .builder()
                                                            .mediaType("x")
                                                            .sample("x")
                                                            .url("x")
                                                            .variableType("x")
                                                            .alt("alt")
                                                            .regex("regex")
                                                            .shortUrl("shortUrl")
                                                            .build()
                                                    )
                                                    .type("x")
                                                    .id(0)
                                                    .build()
                                            )
                                            .build()
                                    )
                                    .whatsapp(
                                        TemplateUpdateParams.Definition.Body.Whatsapp.builder()
                                            .template("template")
                                            .type("type")
                                            .addVariable(
                                                TemplateUpdateParams.Definition.Body.Whatsapp
                                                    .Variable
                                                    .builder()
                                                    .name("x")
                                                    .props(
                                                        TemplateUpdateParams.Definition.Body
                                                            .Whatsapp
                                                            .Variable
                                                            .Props
                                                            .builder()
                                                            .mediaType("x")
                                                            .sample("x")
                                                            .url("x")
                                                            .variableType("x")
                                                            .alt("alt")
                                                            .regex("regex")
                                                            .shortUrl("shortUrl")
                                                            .build()
                                                    )
                                                    .type("x")
                                                    .id(0)
                                                    .build()
                                            )
                                            .build()
                                    )
                                    .build()
                            )
                            .authenticationConfig(
                                TemplateUpdateParams.Definition.AuthenticationConfig.builder()
                                    .addSecurityRecommendation(true)
                                    .codeExpirationMinutes(0)
                                    .build()
                            )
                            .addButton(
                                TemplateUpdateParams.Definition.Button.builder()
                                    .props(
                                        TemplateUpdateParams.Definition.Button.Props.builder()
                                            .activeFor(1)
                                            .countryCode("x")
                                            .offerCode("x")
                                            .phoneNumber("x")
                                            .quickReplyType("x")
                                            .text("text")
                                            .url("x")
                                            .urlType("x")
                                            .autofillText("autofillText")
                                            .otpType("otpType")
                                            .packageName("packageName")
                                            .signatureHash("signatureHash")
                                            .build()
                                    )
                                    .type("x")
                                    .id(0)
                                    .build()
                            )
                            .definitionVersion("definitionVersion")
                            .footer(
                                TemplateUpdateParams.Definition.Footer.builder()
                                    .template("template")
                                    .type("type")
                                    .addVariable(
                                        TemplateUpdateParams.Definition.Footer.Variable.builder()
                                            .name("x")
                                            .props(
                                                TemplateUpdateParams.Definition.Footer.Variable
                                                    .Props
                                                    .builder()
                                                    .mediaType("x")
                                                    .sample("x")
                                                    .url("x")
                                                    .variableType("x")
                                                    .alt("alt")
                                                    .regex("regex")
                                                    .shortUrl("shortUrl")
                                                    .build()
                                            )
                                            .type("x")
                                            .id(0)
                                            .build()
                                    )
                                    .build()
                            )
                            .header(
                                TemplateUpdateParams.Definition.Header.builder()
                                    .template("template")
                                    .type("type")
                                    .addVariable(
                                        TemplateUpdateParams.Definition.Header.Variable.builder()
                                            .name("x")
                                            .props(
                                                TemplateUpdateParams.Definition.Header.Variable
                                                    .Props
                                                    .builder()
                                                    .mediaType("x")
                                                    .sample("x")
                                                    .url("x")
                                                    .variableType("x")
                                                    .alt("alt")
                                                    .regex("regex")
                                                    .shortUrl("shortUrl")
                                                    .build()
                                            )
                                            .type("x")
                                            .id(0)
                                            .build()
                                    )
                                    .build()
                            )
                            .build()
                    )
                    .language(null)
                    .name("Updated Welcome Message")
                    .sandbox(false)
                    .submitForReview(false)
                    .build()
            )

        template.validate()
    }

    @Disabled("Mock server tests are disabled")
    @Test
    fun list() {
        val client = SentOkHttpClient.builder().apiKey("My API Key").build()
        val templateService = client.templates()

        val templates =
            templateService.list(
                TemplateListParams.builder()
                    .page(0)
                    .pageSize(0)
                    .category("category")
                    .isWelcomePlayground(true)
                    .search("search")
                    .status("status")
                    .xProfileId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .build()
            )

        templates.validate()
    }

    @Disabled("Mock server tests are disabled")
    @Test
    fun delete() {
        val client = SentOkHttpClient.builder().apiKey("My API Key").build()
        val templateService = client.templates()

        templateService.delete(
            TemplateDeleteParams.builder()
                .id("7ba7b820-9dad-11d1-80b4-00c04fd430c8")
                .xProfileId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .deleteFromMeta(false)
                .sandbox(false)
                .build()
        )
    }
}
