// File generated from our OpenAPI spec by Stainless.

package dm.sent.models.profiles

import dm.sent.core.http.Headers
import dm.sent.models.brands.BrandData
import dm.sent.models.brands.DestinationCountry
import dm.sent.models.brands.TcrBrandRelationship
import dm.sent.models.brands.TcrVertical
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class ProfileCreateParamsTest {

    @Test
    fun create() {
        ProfileCreateParams.builder()
            .idempotencyKey("req_abc123_retry1")
            .xProfileId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
            .sandbox(false)
            .allowContactSharing(true)
            .allowTemplateSharing(false)
            .billingContact(
                ProfileCreateParams.BillingContact.builder()
                    .email("billing@acmecorp.com")
                    .name("Acme Corp")
                    .address("123 Main Street, New York, NY 10001, US")
                    .phone("+12025551234")
                    .build()
            )
            .billingModel("profile")
            .brand(
                BrandData.builder()
                    .compliance(
                        BrandData.Compliance.builder()
                            .brandRelationship(TcrBrandRelationship.SMALL_ACCOUNT)
                            .vertical(TcrVertical.PROFESSIONAL)
                            .addDestinationCountry(
                                DestinationCountry.builder().id("US").isMain(false).build()
                            )
                            .expectedMessagingVolume("10000")
                            .isTcrApplication(true)
                            .notes(null)
                            .phoneNumberPrefix("+1")
                            .primaryUseCase("Customer notifications and appointment reminders")
                            .build()
                    )
                    .contact(
                        BrandData.Contact.builder()
                            .name("John Smith")
                            .businessName("Acme Corp")
                            .email("john@acmecorp.com")
                            .phone("+12025551234")
                            .phoneCountryCode("1")
                            .role("CEO")
                            .build()
                    )
                    .business(
                        BrandData.Business.builder()
                            .city("New York")
                            .country("US")
                            .countryOfRegistration("US")
                            .entityType(BrandData.Business.EntityType.PRIVATE_PROFIT)
                            .legalName("Acme Corporation LLC")
                            .postalCode("10001")
                            .state("NY")
                            .street("123 Main Street")
                            .taxId("12-3456789")
                            .taxIdType("us_ein")
                            .url("https://acmecorp.com")
                            .build()
                    )
                    .build()
            )
            .description("Sales department sender profile")
            .icon("https://example.com/sales-icon.png")
            .inheritContacts(true)
            .inheritTcrBrand(false)
            .inheritTcrCampaign(false)
            .inheritTemplates(true)
            .name("Sales Team")
            .paymentDetails(
                ProfileCreateParams.PaymentDetails.builder()
                    .cardNumber("4111111111111111")
                    .cvc("123")
                    .expiry("09/27")
                    .zipCode("10001")
                    .build()
            )
            .shortName("SALES")
            .whatsappBusinessAccount(
                ProfileCreateParams.WhatsappBusinessAccount.builder()
                    .accessToken("EAAxxxxxxxxxxxxxxx")
                    .wabaId("123456789012345")
                    .phoneNumberId("987654321098765")
                    .build()
            )
            .build()
    }

    @Test
    fun headers() {
        val params =
            ProfileCreateParams.builder()
                .idempotencyKey("req_abc123_retry1")
                .xProfileId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .sandbox(false)
                .allowContactSharing(true)
                .allowTemplateSharing(false)
                .billingContact(
                    ProfileCreateParams.BillingContact.builder()
                        .email("billing@acmecorp.com")
                        .name("Acme Corp")
                        .address("123 Main Street, New York, NY 10001, US")
                        .phone("+12025551234")
                        .build()
                )
                .billingModel("profile")
                .brand(
                    BrandData.builder()
                        .compliance(
                            BrandData.Compliance.builder()
                                .brandRelationship(TcrBrandRelationship.SMALL_ACCOUNT)
                                .vertical(TcrVertical.PROFESSIONAL)
                                .addDestinationCountry(
                                    DestinationCountry.builder().id("US").isMain(false).build()
                                )
                                .expectedMessagingVolume("10000")
                                .isTcrApplication(true)
                                .notes(null)
                                .phoneNumberPrefix("+1")
                                .primaryUseCase("Customer notifications and appointment reminders")
                                .build()
                        )
                        .contact(
                            BrandData.Contact.builder()
                                .name("John Smith")
                                .businessName("Acme Corp")
                                .email("john@acmecorp.com")
                                .phone("+12025551234")
                                .phoneCountryCode("1")
                                .role("CEO")
                                .build()
                        )
                        .business(
                            BrandData.Business.builder()
                                .city("New York")
                                .country("US")
                                .countryOfRegistration("US")
                                .entityType(BrandData.Business.EntityType.PRIVATE_PROFIT)
                                .legalName("Acme Corporation LLC")
                                .postalCode("10001")
                                .state("NY")
                                .street("123 Main Street")
                                .taxId("12-3456789")
                                .taxIdType("us_ein")
                                .url("https://acmecorp.com")
                                .build()
                        )
                        .build()
                )
                .description("Sales department sender profile")
                .icon("https://example.com/sales-icon.png")
                .inheritContacts(true)
                .inheritTcrBrand(false)
                .inheritTcrCampaign(false)
                .inheritTemplates(true)
                .name("Sales Team")
                .paymentDetails(
                    ProfileCreateParams.PaymentDetails.builder()
                        .cardNumber("4111111111111111")
                        .cvc("123")
                        .expiry("09/27")
                        .zipCode("10001")
                        .build()
                )
                .shortName("SALES")
                .whatsappBusinessAccount(
                    ProfileCreateParams.WhatsappBusinessAccount.builder()
                        .accessToken("EAAxxxxxxxxxxxxxxx")
                        .wabaId("123456789012345")
                        .phoneNumberId("987654321098765")
                        .build()
                )
                .build()

        val headers = params._headers()

        assertThat(headers)
            .isEqualTo(
                Headers.builder()
                    .put("Idempotency-Key", "req_abc123_retry1")
                    .put("x-profile-id", "182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .build()
            )
    }

    @Test
    fun headersWithoutOptionalFields() {
        val params = ProfileCreateParams.builder().build()

        val headers = params._headers()

        assertThat(headers).isEqualTo(Headers.builder().build())
    }

    @Test
    fun body() {
        val params =
            ProfileCreateParams.builder()
                .idempotencyKey("req_abc123_retry1")
                .xProfileId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .sandbox(false)
                .allowContactSharing(true)
                .allowTemplateSharing(false)
                .billingContact(
                    ProfileCreateParams.BillingContact.builder()
                        .email("billing@acmecorp.com")
                        .name("Acme Corp")
                        .address("123 Main Street, New York, NY 10001, US")
                        .phone("+12025551234")
                        .build()
                )
                .billingModel("profile")
                .brand(
                    BrandData.builder()
                        .compliance(
                            BrandData.Compliance.builder()
                                .brandRelationship(TcrBrandRelationship.SMALL_ACCOUNT)
                                .vertical(TcrVertical.PROFESSIONAL)
                                .addDestinationCountry(
                                    DestinationCountry.builder().id("US").isMain(false).build()
                                )
                                .expectedMessagingVolume("10000")
                                .isTcrApplication(true)
                                .notes(null)
                                .phoneNumberPrefix("+1")
                                .primaryUseCase("Customer notifications and appointment reminders")
                                .build()
                        )
                        .contact(
                            BrandData.Contact.builder()
                                .name("John Smith")
                                .businessName("Acme Corp")
                                .email("john@acmecorp.com")
                                .phone("+12025551234")
                                .phoneCountryCode("1")
                                .role("CEO")
                                .build()
                        )
                        .business(
                            BrandData.Business.builder()
                                .city("New York")
                                .country("US")
                                .countryOfRegistration("US")
                                .entityType(BrandData.Business.EntityType.PRIVATE_PROFIT)
                                .legalName("Acme Corporation LLC")
                                .postalCode("10001")
                                .state("NY")
                                .street("123 Main Street")
                                .taxId("12-3456789")
                                .taxIdType("us_ein")
                                .url("https://acmecorp.com")
                                .build()
                        )
                        .build()
                )
                .description("Sales department sender profile")
                .icon("https://example.com/sales-icon.png")
                .inheritContacts(true)
                .inheritTcrBrand(false)
                .inheritTcrCampaign(false)
                .inheritTemplates(true)
                .name("Sales Team")
                .paymentDetails(
                    ProfileCreateParams.PaymentDetails.builder()
                        .cardNumber("4111111111111111")
                        .cvc("123")
                        .expiry("09/27")
                        .zipCode("10001")
                        .build()
                )
                .shortName("SALES")
                .whatsappBusinessAccount(
                    ProfileCreateParams.WhatsappBusinessAccount.builder()
                        .accessToken("EAAxxxxxxxxxxxxxxx")
                        .wabaId("123456789012345")
                        .phoneNumberId("987654321098765")
                        .build()
                )
                .build()

        val body = params._body()

        assertThat(body.sandbox()).contains(false)
        assertThat(body.allowContactSharing()).contains(true)
        assertThat(body.allowTemplateSharing()).contains(false)
        assertThat(body.billingContact())
            .contains(
                ProfileCreateParams.BillingContact.builder()
                    .email("billing@acmecorp.com")
                    .name("Acme Corp")
                    .address("123 Main Street, New York, NY 10001, US")
                    .phone("+12025551234")
                    .build()
            )
        assertThat(body.billingModel()).contains("profile")
        assertThat(body.brand())
            .contains(
                BrandData.builder()
                    .compliance(
                        BrandData.Compliance.builder()
                            .brandRelationship(TcrBrandRelationship.SMALL_ACCOUNT)
                            .vertical(TcrVertical.PROFESSIONAL)
                            .addDestinationCountry(
                                DestinationCountry.builder().id("US").isMain(false).build()
                            )
                            .expectedMessagingVolume("10000")
                            .isTcrApplication(true)
                            .notes(null)
                            .phoneNumberPrefix("+1")
                            .primaryUseCase("Customer notifications and appointment reminders")
                            .build()
                    )
                    .contact(
                        BrandData.Contact.builder()
                            .name("John Smith")
                            .businessName("Acme Corp")
                            .email("john@acmecorp.com")
                            .phone("+12025551234")
                            .phoneCountryCode("1")
                            .role("CEO")
                            .build()
                    )
                    .business(
                        BrandData.Business.builder()
                            .city("New York")
                            .country("US")
                            .countryOfRegistration("US")
                            .entityType(BrandData.Business.EntityType.PRIVATE_PROFIT)
                            .legalName("Acme Corporation LLC")
                            .postalCode("10001")
                            .state("NY")
                            .street("123 Main Street")
                            .taxId("12-3456789")
                            .taxIdType("us_ein")
                            .url("https://acmecorp.com")
                            .build()
                    )
                    .build()
            )
        assertThat(body.description()).contains("Sales department sender profile")
        assertThat(body.icon()).contains("https://example.com/sales-icon.png")
        assertThat(body.inheritContacts()).contains(true)
        assertThat(body.inheritTcrBrand()).contains(false)
        assertThat(body.inheritTcrCampaign()).contains(false)
        assertThat(body.inheritTemplates()).contains(true)
        assertThat(body.name()).contains("Sales Team")
        assertThat(body.paymentDetails())
            .contains(
                ProfileCreateParams.PaymentDetails.builder()
                    .cardNumber("4111111111111111")
                    .cvc("123")
                    .expiry("09/27")
                    .zipCode("10001")
                    .build()
            )
        assertThat(body.shortName()).contains("SALES")
        assertThat(body.whatsappBusinessAccount())
            .contains(
                ProfileCreateParams.WhatsappBusinessAccount.builder()
                    .accessToken("EAAxxxxxxxxxxxxxxx")
                    .wabaId("123456789012345")
                    .phoneNumberId("987654321098765")
                    .build()
            )
    }

    @Test
    fun bodyWithoutOptionalFields() {
        val params = ProfileCreateParams.builder().build()

        val body = params._body()
    }
}
